export const WEATHER_CONDITIONS = {
  THUNDERSTORM: 'Thunderstorm',
  DRIZZLE: 'Drizzle',
  RAIN: 'Rain',
  SNOW: 'Snow',
  CLEAR: 'Clear',
  CLOUDS: 'Clouds',
  MIST: 'Mist',
  SMOKE: 'Smoke',
  HAZE: 'Haze',
  DUST: 'Dust',
  FOG: 'Fog',
  SAND: 'Sand',
  ASH: 'Ash',
  SQUALL: 'Squall',
  TORNADO: 'Tornado',
};

export const WEATHER_ICONS = {
  '01d': '☀️',
  '01n': '🌙',
  '02d': '⛅',
  '02n': '☁️',
  '03d': '☁️',
  '03n': '☁️',
  '04d': '☁️',
  '04n': '☁️',
  '09d': '🌧️',
  '09n': '🌧️',
  '10d': '🌦️',
  '10n': '🌧️',
  '11d': '⛈️',
  '11n': '⛈️',
  '13d': '❄️',
  '13n': '❄️',
  '50d': '🌫️',
  '50n': '🌫️',
};